baseurl = "http://www.csim.dev/"
languageCode = "en-us"
title = "Clint Simon"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright"

[taxonomies]
  tag = "tags"
  
[params]
    # Social accounts. Link to these accounts are displayed in the header and
    image = ""
    headercolor = "#af200a"
    # footer.
    twitter = "clintsim"
    github = "csim"
    linkedin = "clintsimon"
    googleplus = ""
    facebook = "csim74"
    stackoverflow = ""
    keybase = ""
    instagram = ""
    # Disqus shortname
    disqus = "clintsimon"
    # Google Analytics API key.
    ga_api_key = "UA-25860409-1"
    # Mixpanel API key.
    mixpanel_api_key = ""
    author = "Clint Simon"
    avatar = ""
    contact = ""
    bio = ""
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "Find a way."
    themecolor = "#af200a" # Defines the tab color in Chrome for Android.